# Generated by Django 5.1.2 on 2024-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='barber_email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='barber_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='barber_phone',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='wallet_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
